version: '3.8'
services:

  mongo-product_service:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-product-service-data:/data/db
    networks:
      - default

  mongo-inventory_service:
    image: mongo:6-jammy
    ports:
      - "27018:27017"
    expose:
      - "27018"
    volumes:
      - ./mongo-inventory-service-data:/data/db
    networks:
      - default

#networks:
#  default: